# ~/.config/containers/registries.conf.d/50-k3s.conf
# /etc/containers/registries.conf.d/
[[registry]]
prefix = "*.localhost"
insecure = true

[[registry]]
prefix = "*.cluster.internal"
insecure = true
